### ISSUE TITLE
Not working for plain textarea fields in repeaters.

### ISSUE THREAD

**Issue by duerrsimon** [SkyLundy/Fluency-Translation#2]
I get the following error on a plain text field inside a repeater:
```
Uncaught ReferenceError: CKEDITOR is not defined
    at HTMLAnchorElement.<anonymous> (fluency.js:257)
```

You should probably be doing something like this:

``` javascript
      try {
        if (CKEDITOR != undefined && CKEDITOR.instances[targetInput.id]){
          // Get the source field ID from the target field ID by removing
          // the target input ID from the end
          sourceCkeditor = CKEDITOR.instances[targetInput.id.split('__')[0]]
          targetCkeditor = CKEDITOR.instances[targetInput.id]
          contentToTranslate = sourceCkeditor.document.getBody().getHtml()
        }
      } catch (e){
        console.log('no CK editor')
      } 
      if (contentToTranslate=== null){
        contentToTranslate = sourceInput.value
      }
```

**Comment by SkyLundy** [comment]
@duerrsimon Thanks for catching this, missed it after refactoring. I'll patch and push an update tonight.

**Comment by SkyLundy** [comment]
Just pushed the updated version 0.2.5 with this fix.

This list of commits is a mess because I pushed/tagged incorrectly last night while tired. Still tired, but at least it's fixed...

**Comment by ivangretsky** [comment]
Hey, @SkyLundy!

I am having same bug with Repeater Matrix fields in 0.3.2. Could you please reopen this. Or should I create a new issue?
