### ISSUE TITLE
Add support for free api

### ISSUE THREAD

**Issue by duerrsimon** [SkyLundy/Fluency-Translation#3]
DeepL also has a free api with 500 000 characters translation. 

Seems to work fine by changing this line: 

`classes/DeepL.class.php:    $reqUrl = "https://api-free.deepl.com/v2{$endpoint}?auth_key={$this->apiKey}";`

Maybe you want to add a toggle in the options whether the free api or the pro api should be used?

**Comment by SkyLundy** [comment]
@duerrsimon Excellent idea. I didn't know they had a free API, might not have been a thing when I originally wrote the module. I'll add this.

**Comment by SkyLundy** [comment]
This feature has been added in v0.3.0 and is available now on the main branch/latest release.
