### ISSUE TITLE
Change the hard-coded label "Translate from English"

### ISSUE THREAD

**Issue by Clarity157** [SkyLundy/Fluency-Translation#7]
Hello, @SkyLundy!

Could you please change the hard-coded label "Translate from English" to "Translate from {source language}"?

**Comment by SkyLundy** [comment]
I will add that update to the module!

In the meantime if you want a quick fix then go to /src/js/fluency.js and edit line 216 to say whatever you would like. If you update in the future your changes will be overridden but it will show the proper text as expected.

**Comment by Clarity157** [comment]
Thank you!

**Comment by SkyLundy** [comment]
@Clarity157 Next release will have all Translator related UI text customizable and translatable within the admin. I'll post a comment in the Fluency thread on the ProcessWire forums when I push the new version. Keep an eye out!
